### ISSUE TITLE
SDK saves --stactrace property as repository name

### ISSUE THREAD

**Issue by Mihail063** [cuba-platform/cuba-sdk#55]
### Environment

- Plugin version: 0.3-SNAPSHOT

### Description of the bug or enhancement

1. Run the SDK 
2. Run the `repository add source --stactrace` command

AR:  SDK saved `--stactrace` as name

**Comment by zaharchenko-evgeny** [comment]
error in `--stactrace` parameter, should be `--stacktrace`
