### ISSUE TITLE
Ability to upgrade embedded repository in setup-nexus command

### ISSUE THREAD

**Issue by zaharchenko-evgeny** [cuba-platform/cuba-sdk#67]
`setup-nexus` command should ask to upgrade repository if repository already exists

**Comment by Mihail063** [comment]
Failed to unzip Nexus repository after trying to upgrade repository version to 3.27. 0-03
![изображение](https://user-images.githubusercontent.com/24281695/92613142-a9d7da80-f2cb-11ea-986a-20a0f95d5ed1.png)

**Comment by Mihail063** [comment]
Problem still reproduce.

**Comment by zaharchenko-evgeny** [comment]
Please try to remove `nexus.zip` from SDK home folder
