### ISSUE TITLE
Adapt to Jmix

### ISSUE THREAD

**Issue by alexbudarov** [cuba-platform/cuba-sdk#72]
- Adapt to Jmix module structure, artifacts
- Delete usages of Bintray and JCenter (they will be shutdown soon).
- Move repository closer to Jmix.

**Comment by artemglinov** [comment]
## Progress

2021-08-16: 20%

- [] Analyze the project, find the necessary Jmix dependencies
- [] JmixProvider (+subclasses JmixFrameworkProvider and JmixAddonProvider)
- [] NexusSearchComponentProvider
- [] Jmix support in CLI commands

**Comment by artemglinov** [comment]
The screenshots of Readme file don't correspond to the new features. They should be fixed.
